In [12]:
import pandas as pd
import re
import string
from string import punctuation
import nltk
from nltk.corpus import stopwords
import Sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
#import data from covid-sentiment.csv
tw_df = pd.read_csv('archive(5)\covid-sentiment.csv')
tw_df.head(3)

,conversation_id,date,time,user_id,username,tweet,mentions,replies_count,retweets_count,likes_count,hashtags
0,1258425982907637761,2020-05-07,23:58:29,1058474317,monologis_id,https://bit.ly/2L6CcbB | Seharusnya saat ini...,[],0,3,0,[]
1,1258320972198940675,2020-05-07,23:57:30,1179769476,its_dul,Klo kata gw Pemerintah tuh lagi menerapkan Her...,['mas__piyuuu'],0,0,0,[]
2,1258356644427083777,2020-05-07,23:53:20,1012156669831229441,meonkbaong,Saat ini yang bisa saya lakukan hanya menyiapk...,['oiivert'],0,0,0,[]

In [36]:
#preprocessing tweet data

#making all letter lowercase
tweet = [x.lower() for x in  tw_df['tweet']]

#remove url
#all pattern start from http and end in whitspace will be removed
tweet = [re.sub(r'http\S+'," ",x) for x in tweet]

#remove twitter pic
#all pattern start from pic.twitter.com and end in whitspace will be removed
tweet = [re.sub(r'pic.twitter.com\S+'," ",x) for x in tweet]

#remove whitespace
tweet = [x.strip() for x in  tweet]

In [37]:
# remove punctuation and tokenization in one go
#all character from a-Z and 0-9 will not be removed
punc_filter = nltk.RegexpTokenizer(r"\w+")

tweet = [punc_filter.tokenize(x) for x in tweet]

tweet[0]

In [45]:
#collect the stopwords 
stop_words = stopwords.words('Indonesian')
factory = StemmerFactory()
stemmer = factory.create_stemmer()


#stopwrods removal 
nonstop_words = []
for stc in  tweet:
    words = [x for x in stc if x not in stop_words]
    
    nonstop_words.append(words)

nonstop_words[0]

# rejoin the list of words to make sentences
tweet = nonstop_words
text_tweet = [" ".join(x) for x in tweet]
text_tweet[0]

'pemerintah lampung bantuan mahasiswa derasnya donasi masuk pemprov lampung tim gugus tugas covid 19'

In [47]:
# make bag of words
bow = CountVectorizer()

#fit text_tweet to bow
x_sentence = bow.fit_transform(text_tweet)

#get feature names from bow
x_sentence_df = pd.DataFrame(x_sentence.toarray(),columns=bow.get_feature_names())
x_sentence_df[5]

In [64]:
#making tfidf vectorizer
tfidf = TfidfVectorizer()

#create new list with fewer sentence so memory will fit
text_tweet2 = text_tweet[0:15000]

#fit text_tweet2 to tfidf
x2_sentence = tfidf.fit_transform(text_tweet2)

#get frequency count of each feature names
x2_sentence_df = pd.DataFrame(x2_sentence.toarray(),columns=tfidf.get_feature_names())
x2_sentence_df.head(5)

,00,000,002,006,007,008,00wib,01,011,012,...,𝗣𝗲𝗹𝗶𝗱𝘂𝗻𝗴,𝗥𝗮𝘁𝘂𝘀𝗮𝗻,𝗦𝗲𝘁,𝗱𝗮𝗻,𝗱𝗶𝗮𝘄𝗮𝘀𝗶,𝗱𝗶𝗸𝗼𝗻𝘁𝗿𝗼𝗹,𝗵𝗮𝗿𝘂𝘀,𝘀𝗶𝗮𝗽,𝘂𝗻𝘁𝘂𝗸,𝟭𝟵
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0